# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{congress_scrapper}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Canx"]
  s.date = %q{2011-04-06}
  s.description = %q{Wrapper para acceder a las propuestas del Congreso (congreso.es)}
  s.email = %q{canchete@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "lib/scrapper.rb",
    "lib/scrapper/form.rb",
    "lib/scrapper/initiative.rb",
    "lib/scrapper/initiative_factory.rb",
    "script/destroy",
    "script/generate",
    "spec/cassettes/form_date.yml",
    "spec/cassettes/form_submit.yml",
    "spec/cassettes/form_title.yml",
    "spec/cassettes/form_type.yml",
    "spec/cassettes/initiative_title.yml",
    "spec/cassettes/page_empty.yml",
    "spec/cassettes/page_multiple46.yml",
    "spec/cassettes/page_single22.yml",
    "spec/scrapper/form_spec.rb",
    "spec/scrapper/initiative_factory_spec.rb",
    "spec/scrapper_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/Canx/congress_scrapper}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Wrapper para acceder a las propuestas del Congreso (congreso.es)}
  s.test_files = [
    "spec/scrapper/form_spec.rb",
    "spec/scrapper/initiative_factory_spec.rb",
    "spec/scrapper_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mechanize>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<mechanize>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<mechanize>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<mechanize>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<mechanize>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<mechanize>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

